version: '3.8'

services:
  aie-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./AIE/AIE:/inetpub/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development