//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIE.Content.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesAPI : DbContext
    {
        public EntitiesAPI()
            : base("name=EntitiesAPI")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<qryApiContactU> qryApiContactUs { get; set; }
        public virtual DbSet<qryApiUser> qryApiUsers { get; set; }
        public virtual DbSet<qryApiUserLogin> qryApiUserLogins { get; set; }
        public virtual DbSet<APICountDown> APICountDowns { get; set; }
    }
}
